version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - /Users/qpjoy/data/redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-client
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379 # Connect to the Redis container
# volumes:
#   redis_data:
