# # Build stage
# FROM node:20.18-alpine AS builder
# WORKDIR /app
# COPY . .
# RUN yarn install --frozen-lockfile
# RUN yarn build
# # RUN ls -al ./node_modules/
# # RUN /app/node_modules/.bin/nest build
# # CMD ["./node_modules/.bin/nest", "build"]

# Runtime stage
FROM node:20.18-alpine
WORKDIR /app
COPY package.json ./
RUN yarn install --verbose
COPY . .


ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "dist/apps/pdf/main"]