# Build stage
FROM node:20.18-alpine AS builder
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile --production && yarn build

# Runtime stage
FROM node:20.18-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "dist/main"]