FROM node:20.18-alpine AS office_fe
# Install pnpm
RUN npm i vite -g
WORKDIR /app
RUN ls -al
COPY .npmrc .
COPY package.json .
RUN yarn install --verbose
RUN ls -al
COPY . .
RUN yarn build
# RUN mv dist pushcode && mkdir dist && mv pushcode dist/


# EXPOSE 5173

# CMD ["yarn", "dev"]
FROM nginx:alpine
COPY --from=office_fe /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]