services:
  postfix:
    image: boky/postfix
    container_name: postfix
    hostname: mail
    environment:
      - POSTFIX_myhostname=mail.memoscard.com
      - POSTFIX_mydomain=memoscard.com
      - POSTFIX_smtp_tls_security_level=may
      - POSTFIX_smtp_tls_loglevel=1
      - POSTFIX_message_size_limit=30720000
      - SMTP_USERNAME=admin@memoscard.com
      - SMTP_PASSWORD=adminpassword
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./data/maildata:/var/spool/postfix
    restart: always

  dovecot:
    image: tvial/dovecot
    container_name: dovecot
    ports:
      - "143:143"
    volumes:
      - ./dovecot/dovecot.conf:/etc/dovecot/dovecot.conf:ro
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postfix
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot:/etc/letsencrypt
    entrypoint: >
      certbot certonly --standalone --noninteractive --agree-tos --email admin@memoscard.com -d mail.memoscard.com
    restart: "no"

  node:
    build: ./node
    container_name: mailer
    depends_on:
      - postfix
    environment:
      - SMTP_HOST=postfix
      - SMTP_PORT=587
      - SMTP_USER=admin@memoscard.com
      - SMTP_PASS=adminpassword
    command: ["node", "sendMail.js"]
