services:
  mail:
    image: tozd/mail
    container_name: mail
    hostname: mail
    domainname: memoscard.com
    restart: always
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./data/mail:/var/lib/mail
      - ./data/acme:/var/lib/acme
      - ./data/letsencrypt:/etc/letsencrypt
      - ./secrets:/etc/keys
    environment:
      - MAILNAME=mail.memoscard.com
      - VIRTUAL_DOMAINS=memoscard.com
      - USERS=admin@memoscard.com
      - SMTP_PASSWORD_FILE=/etc/keys/smtp_password
      - DKIM_SELECTOR=mail
      - DKIM_DOMAINS=memoscard.com
      - DKIM_PRIVATE_KEY_FILE=/etc/keys/dkim_private.key
      - LETSENCRYPT_EMAIL=admin@memoscard.com
      - RELAY_NETWORKS=192.168.0.0/16 172.0.0.0/8 127.0.0.0/8
      - TLS_POLICY_LEVEL=encrypt
    cap_add:
      - NET_ADMIN

  mailer:
    build: ./mailer
    container_name: mailer
    depends_on:
      - mail
    environment:
      - SMTP_HOST=mail
      - SMTP_PORT=587
      - SMTP_USER=admin@yourdomain.com
      - SMTP_PASS=adminpassword
      - SMTP_FROM=admin@yourdomain.com
      - SMTP_TO=test@receiver.com
    command: ["node", "sendMail.js"]
