version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    # expose:
    #   - 5432
    ports:
      - 4057:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_example
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      #     - postgres-data:/var/lib/postgresql/data
      - /Users/qpjoy/data/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: qpjoy.pgadmin
    image: qpjoy/pgadmin
    build:
      context: .
      dockerfile: pgadmin.dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4904
      # Allow pgAdmin to connect to any host
      # PGADMIN_LISTEN_ADDRESS: "*:*"
    volumes:
      - /Users/qpjoy/data/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 4904:4904
    restart: unless-stopped
# volumes:
#   postgres-data:
#   pgadmin-data:
