version: "3.3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www.memoscard.com.key:/etc/nginx/cert/www.memoscard.com.key
      - ./www.memoscard.com.pem:/etc/nginx/cert/www.memoscard.com.pem
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./websites.conf:/etc/nginx/conf.d/websites.conf
      # need change ~ to workspace path in production
      - ~/workspace/websites/:/var/www/html/websites/
