version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
      # - node_modules:/app/node_modules/
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSWL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
