services:
  office-fe:
    container_name: qpjoy.office-fe
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    depends_on:
      - office-be
    ports:
      - 5173:5173
    networks:
      - office
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # - /app/node_modules # prevent host/node_modules overwrite
    command: yarn dev

  office-be:
    container_name: qpjoy.office-be
    # image: qpjoy/office-be
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - 9101:3000
    networks:
      - office
    volumes:
      - ./be:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev

  db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdf
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      #     - postgres-data:/var/lib/postgresql/data
      - /Users/qpjoy/data/pdf-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - office

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - 4904:4904
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4904
      # Allow pgAdmin to connect to any host
      # PGADMIN_LISTEN_ADDRESS: "*:*"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
    volumes:
      # TODO: chown -R 5050:5050 /Users/qpjoy/data/pgadmin-data
      #       SEE .build.yml
      # - D:/data/pgadmin-data:/var/lib/pgadmin
      - /Users/qpjoy/data/pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - office
networks:
  office:
